config/routes.rb
Mybenkyoukai::Application.routes.draw do

  get "calendar/index", as: :calendar_index
  get "calendar/download/:site/:title" => "calendar#download", as: :calendar_download
  post "calendar/make", as: :calendar_make
  

  root 'calendar#index'

  

end

app/models/benkyoukai.rb
class Benkyoukai < ActiveRecord::Base

  validates_uniqueness_of :title, :scope => :site

  scope :site, lambda{|s| where("site = ?", s) }
  scope :title, lambda{|t| where("title = ?", t) }
  
  KOKUCHEESE = "kokucheese"
  DOORKEEPER = "doorkeeper"
  
  class << self
  
    def supported_sites
      [
        ["こくちーず", KOKUCHEESE],
        ["Doorkeeper", DOORKEEPER],
      ]
    end
    
    
    def benkyoukai_with_site_and_title site, title
      b = nil
      begin
        unless site.blank? || title.blank?
          b = Benkyoukai.site(site).title(title).first
          unless b
            case site
            when KOKUCHEESE
              k = Kokucheese.new title
              b = k.benkyoukai
            when DOORKEEPER
              d = Doorkeeper.new title
              b = d.benkyoukai
            end
          end
        end
      rescue => e
p e
        b = nil
      end
      b
    end
  

    def update_all
      Benkyoukai.all.each do |b|
        b.update
      end
    end

  end
      

  def update
    service.new(self).update
  end


  private

    def service
      case site
      when KOKUCHEESE
        Kokucheese
      when DOORKEEPER
        Doorkeeper
      else
        nil
      end
    end
end

app/models/doorkeeper.rb
class Doorkeeper

  attr_reader :ics, :group, :title, :url, :events, :prefecture
  attr_reader :benkyoukai
  
  def initialize arg
    case arg
    when /^http:\/\/(.+)\.doorkeeper\.jp/
      @group = $1
    when String
      @group = get_group_of_title arg
    when Benkyoukai
      @benkyoukai = arg
      /^http:\/\/(.+)\.doorkeeper\.jp/ =~ @benkyoukai.source_url
      @group = $1
      @title = @benkyoukai.title
    end
    analize
  end
  
  def benkyoukai
    unless @benkyoukai
      @benkyoukai = Benkyoukai.site(Benkyoukai::DOORKEEPER).title(title).first
      unless @benkyoukai
        @benkyoukai = Benkyoukai.create(site:Benkyoukai::DOORKEEPER, title:title, source_url:url, ics:ics, prefecture:prefecture)
      end
    end
    @benkyoukai
  end
  
  def update
    b = benkyoukai
    b.ics = ics
    b.save
  end

  

  private
  
  def analize
    get_events
    make_ical
  end
  
  def events_url
    "http://api.doorkeeper.jp/groups/#{group}/events"
  end
  
  def get_group_of_title title
    url = "http://api.doorkeeper.jp/events?q=#{URI.escape(title)}"
    s = open(url){|f| f.read}
    @events = JSON.load(s)
    event = @events.first["event"]
    if event
      /^http:\/\/(.+)\.doorkeeper\.jp/ =~ event["group"]["public_url"]
      $1
    else
      nil
    end
  end

  def get_events
    s = open(events_url){|f| f.read}
    @events = JSON.load(s)
    event = @events.first["event"]
    if event
      @title = event["group"]["name"]
      @url = event["group"]["public_url"]
    end
  end
  
  def make_ical
    cal = Icalendar::Calendar.new
    tzid = Time.zone.name
    events.each do |event|
      event = event["event"]
      e = cal.event  # 新規eventがcalに追加され、それが返される
      
      # to_datetimeではnsecがないと出るのでDateTime.newを使っている
      t = Time.iso8601(event["starts_at"]).in_time_zone(Time.zone)
      t = DateTime.new t.year, t.month, t.day, t.hour, t.min
      e.dtstart = Icalendar::Values::DateTime.new t, 'tzid' => tzid
      
      t = Time.iso8601(event["ends_at"]).in_time_zone(Time.zone)
      t = DateTime.new t.year, t.month, t.day, t.hour, t.min
      e.dtend = Icalendar::Values::DateTime.new t, 'tzid' => tzid
      
      e.summary = event["title"]
      e.description = event["title"]
      e.location = [event["address"], event["venue_name"]].join(" ")
      e.ip_class = "PRIVATE"
    end
    @ics = cal.to_ical
  end

end

app/models/kokucheese.rb
class Kokucheese

  attr_reader :url
  attr_reader :title, :ics, :index_url, :prefecture, :description
  attr_reader :benkyoukai
  
  def initialize arg
    case arg
    when /^http:\/\//i
      @url = arg
    when String
      @url = "http://kokucheese.com/main/host/#{arg}/"
      @index_url = @url
      @title = arg
    when Benkyoukai
      @benkyoukai = arg
      @index_url = @benkyoukai.source_url
      @title = @benkyoukai.title
    else
      raise "Invalid argument #{arg}"
    end
    analize
  end
  
  def benkyoukai
    unless @benkyoukai
      @benkyoukai = Benkyoukai.site(Benkyoukai::KOKUCHEESE).title(title).first
      unless @benkyoukai
        @benkyoukai = Benkyoukai.create(site:Benkyoukai::KOKUCHEESE, title:title, source_url:index_url, ics:ics, prefecture:prefecture)
      end
    end
    @benkyoukai
  end
  
  def update
    b = benkyoukai
    b.ics = ics
    b.save
  end

  private

  def analize
    if @index_url.nil? || @title.nil?
      @index_url, @title = get_index_url
      unless @index_url && @title
        raise "Couldn't get title"
      end
    end
    make_ical get_events
  end
  
  def get_events
    doc = Nokogiri::HTML(open(index_url))

    # イベントは.veventで取得できる
    doc.search(".vevent").map do |event_info|
    
      detail_url = event_info
          .search("a.article.summary").first["href"]
#p detail_url
#      get_event detail_url

      # 日付は.event_dateで取得
      a = event_info
          .search(".event_date").inner_text.gsub("\r\n", "")
          .scan(/(\d+)年(\d+)月(\d+)日/)
          .flatten
          .map{|e| e.to_i}
      date = Date.new(*a)
      
  
      name = event_info.search(".event_name").inner_text
      @prefecture = event_info.search("td.event_prefecture.location").inner_text
      description = event_info.search("td.event_description").inner_text.gsub("__", "")

      { date:date, name:name, description:description, prefecture:@prefecture }
    end
  end
  
  def get_event url
    doc = Nokogiri::HTML(open(url))
    doc.search("table.indexTable").each do |table|
      table.search("tr").each do |tr|
        p tr.search("th").inner_text
        p tr.search("td").inner_text
      end
    end
  end
  
  
  def get_index_url
    doc = Nokogiri::HTML(open(url))

    a = doc.search("a").map do |a|
      url = a["href"]
      if /http:\/\/kokucheese.com\/main\/host\/([^\/]+)/ =~ url
        [url, URI.unescape($1)]
      end
    end.select{|a| a}
    a.first
  end

  def make_ical events
    cal = Icalendar::Calendar.new
    events.each do |event|
      e = cal.event  # 新規eventがcalに追加され、それが返される
      e.dtstart = Icalendar::Values::Date.new(event[:date].strftime("%Y%m%d"))
      e.dtend = Icalendar::Values::Date.new(event[:date].strftime("%Y%m%d"))
      e.summary = event[:name]
      e.description = event[:description]
      e.ip_class = "PRIVATE"
    end
    @ics = cal.to_ical
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @site = params["site"]
    @title = params["title"]
    @benkyoukai = nil
    unless @site.blank? || @title.blank?
      @benkyoukai = Benkyoukai.benkyoukai_with_site_and_title @site, @title
      if @benkyoukai
        @download_url = calendar_download_url(@benkyoukai.site, @benkyoukai.title.gsub(/\./, "%2E"), format:"ics")
      end
    end
    @sites = Benkyoukai.supported_sites
  end
  
  def make
    site = params["site"]
    title = params["title"]
    benkyoukai = Benkyoukai.benkyoukai_with_site_and_title site, title

    if benkyoukai
      redirect_to calendar_index_path site:benkyoukai.site, title:benkyoukai.title
    else
      redirect_to calendar_index_path(site:site, title:title), alert: "#{title}は見つかりませんでした"
    end
  end
  
  def download
    site = params["site"]
    title = params["title"]
    benkyoukai = Benkyoukai.benkyoukai_with_site_and_title site, title

    if benkyoukai
      render text: benkyoukai.ics
    else
      render text: nil #"該当する勉強会はありません。"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/views/calendar/index.html.haml
%h1 毎勉強会

.summary
  毎勉強会は勉強会などのイベント開催日をサービスしてるサイトからイベントを取得しカレンダー形式(ics)のデータを提供するサービスです。
%h2 使い方
.usage
  現在対応しているサービスは#{link_to "こくちーず", "http://kokucheese.com", target:"_blank"}と#{link_to "Doorkeeper", "http://www.doorkeeperhq.com", target:"_blank"}です。
  %br
  勉強会の名称に、こくちーずの場合は主催にある名称を入力します。Doorkeeperの場合はイベントのコミュニティ名を入力します。
  %br
  %br
  該当する勉強会があると、URLが表示されます。
  %br
  Macのカレンダーアプリの場合は、ファイルメニューから新規参照カレンダー... で表示されるダイアログのカレンダーのURLに入力します。
  %br
  %br

.form
  = form_tag calendar_make_path do
    .field
      = label_tag :site, "サービス"
      = select_tag :site, options_for_select(@sites, @site)
    .field
      = label_tag :title, "勉強会の名称"
      = text_field_tag :title, @title
    .actions
      = submit_tag "検索"
    

- if @benkyoukai
  #{@benkyoukai.title}は以下のURLを購読して下さい。
  %br
  = link_to @download_url, @download_url
  %br
  更新日 #{@benkyoukai.updated_at}

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "毎勉強会"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") 毎勉強会
          !!!.container.nav-collapse
          !!!  %ul.nav
          !!!    %li= link_to "Link 1", "/path1"
          !!!    %li= link_to "Link 2", "/path2"
          !!!    %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        .sapn2
        !!!.span3
        !!!  .well.sidebar-nav
        !!!    %ul.nav.nav-list
        !!!      %li.nav-header Sidebar
        !!!      %li= link_to "Link 1", "/path1"
        !!!      %li= link_to "Link 2", "/path2"
        !!!      %li= link_to "Link 3", "/path3"
        .span8
          = bootstrap_flash
          = yield
        .span2
    
      %footer
        %hr
        .row-fluid
          .span1
          .span10
            %p &copy; 2014 #{link_to "Akita Ruby Meeting(秋田Rubyお楽しみ会)", "http://akitarubymeeting.doorkeeper.jp", target:"_blank"}
          .span1